replicaCount: 1

image:
  repository: netdata/netdata
  tag: v1.11.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ## If you use NodePort and want to use a personal port. You have to set nodePort
  # nodePort: 32111
  port: 19999
  annotations: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - netdata.k8s.local
  tls:
    - secretName: netdata-tls
      hosts:
        - netdata.k8s.local

master:
  resources: {}
    # limits:
    #  cpu: 4
    #  memory: 4096Mi
    # requests:
    #  cpu: 4
    #  memory: 4096Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}
  env: {}

slave:
  resources: {}
    # limits:
    #  cpu: 4
    #  memory: 4096Mi
    # requests:
    #  cpu: 4
    #  memory: 4096Mi

  nodeSelector: {}

  tolerations:
    - operator: Exists
      effect: NoSchedule

  affinity: {}
  env: {}
