apiVersion: v1
kind: Service
metadata:
  name: {{ template "netdata.name" . }}
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: master
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and ( eq .Values.service.type  "NodePort" ) ( .Values.service.nodePort ) }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  selector:
    app: {{ template "netdata.name" . }}
    release: {{ .Release.Name }}
    role: master
